services:
  temp-postgres-1:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase1'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  temp-postgres-2:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase2'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'